app:
  name: go-practice
  port: 9990

crypto:
  current: "5YSvRvUHg="
  old:     "2V1Evn8e8="

jwt:
  current_key_id: "2025-08"
  current_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDVGsiuF9iv45/h...
    -----END PRIVATE KEY-----
  old_key_id: "2024-08"
  old_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDOuy8tHIMW+Ljg...
    -----END PRIVATE KEY-----

host:
  test: "127.0.0.1:3000"

tencent_cloud:
  secret_id: ""
  secret_key: ""
  region: "ap-beijing"
  sms:
    sdk_app_id: ""
    sign_name: ""
  ses:
    from_email: ""

mysql:
  default:
    master:
      - "database:password@tcp(127.0.0.1:3306)/tablename"
    slave:
      - "database:password@tcp(127.0.0.1:3306)/tablename"
    max_idle_conns: 100
    max_open_conns: 200
    conn_max_lifetime: 300

redis:
  default:
    addrs:
      - "127.0.0.1:6379"
    password: ""
    db: 0
    pool_size: 20
    min_idle_conns: 10

kafka:
  default: 
    brokers: 
      - "127.0.0.1:9092"
    topic: "topic-test"
    group_id: "group-test"
